
development:
  <<: *default
  adapter: mysql2
  host: localhost
  username: root
  password: root
  database: padma
 

production:
  <<: *default
  adapter: mysql2
  host: localhost
  username: root
  password: root
  database: padma
