# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0cd32c44b1be4b6bb631a84382137f7f5e3c871a514a9b523abc21fe177b7e9c0904a85ec64d6e35cdcadc3790f67618094e9274490dfc85e7400fc811493bd

test:
  secret_key_base: 65d750e77459858ddec3ab39bcc9661e084548bc541681115cc02de04317c328b506e3364dc4849335d373db4ac58189ad96154b6ac8a18263fac228ac5315b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
